In [1]:
import numpy as np

In [2]:
rand(2,3)

NameError: name 'rand' is not defined

In [3]:
np.random.rand(2,3)

array([[0.36765569, 0.94833911, 0.20683233],
       [0.40333654, 0.2263858 , 0.28027883]])

In [4]:
np.random.rand(3)

array([0.97637687, 0.02797703, 0.25624489])

In [6]:
np.random.randint(3)

2

In [11]:
np.random.randint(2,10)

9

In [8]:
np.random.randint(2,10,4)

array([5, 5, 5, 5])

In [12]:
np.random.randint(-30,20,10)

array([ -9, -20,   3,  16,  -3,  -9,  14,   8,   6,  14])

In [13]:
np.random.randint(10,40,(10,10))

array([[32, 18, 25, 23, 31, 38, 23, 21, 16, 21],
       [20, 31, 31, 36, 19, 19, 31, 35, 34, 12],
       [10, 16, 26, 10, 33, 27, 13, 20, 20, 25],
       [24, 13, 39, 23, 20, 27, 38, 24, 21, 24],
       [11, 13, 13, 20, 13, 33, 26, 38, 35, 11],
       [17, 18, 34, 11, 36, 24, 13, 11, 21, 21],
       [16, 17, 37, 28, 24, 24, 13, 30, 16, 35],
       [25, 33, 39, 20, 34, 13, 38, 10, 34, 34],
       [22, 23, 17, 37, 14, 38, 18, 25, 37, 13],
       [35, 26, 28, 33, 17, 21, 33, 38, 39, 12]])

In [14]:
m = np.random.randint(10,40,(10,10))
m

array([[26, 17, 14, 38, 24, 31, 38, 27, 17, 18],
       [39, 19, 16, 10, 37, 11, 28, 19, 24, 33],
       [26, 13, 37, 11, 33, 24, 26, 12, 29, 14],
       [30, 34, 36, 18, 36, 28, 16, 22, 21, 19],
       [12, 20, 37, 20, 30, 29, 17, 24, 28, 32],
       [29, 26, 36, 26, 18, 11, 35, 36, 20, 21],
       [30, 34, 34, 14, 35, 23, 35, 39, 29, 34],
       [19, 20, 33, 26, 18, 15, 12, 10, 27, 10],
       [22, 28, 14, 18, 33, 13, 17, 25, 30, 30],
       [17, 24, 19, 29, 34, 13, 34, 13, 29, 22]])

In [16]:
my_list =[0,1,2,3,4,5]
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [18]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [20]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [21]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

**Slicing in matrix**

In [22]:
m

array([[26, 17, 14, 38, 24, 31, 38, 27, 17, 18],
       [39, 19, 16, 10, 37, 11, 28, 19, 24, 33],
       [26, 13, 37, 11, 33, 24, 26, 12, 29, 14],
       [30, 34, 36, 18, 36, 28, 16, 22, 21, 19],
       [12, 20, 37, 20, 30, 29, 17, 24, 28, 32],
       [29, 26, 36, 26, 18, 11, 35, 36, 20, 21],
       [30, 34, 34, 14, 35, 23, 35, 39, 29, 34],
       [19, 20, 33, 26, 18, 15, 12, 10, 27, 10],
       [22, 28, 14, 18, 33, 13, 17, 25, 30, 30],
       [17, 24, 19, 29, 34, 13, 34, 13, 29, 22]])

In [25]:
b = np.random.randint(10,20,(5,4))
b

array([[15, 14, 17, 19],
       [19, 13, 13, 16],
       [17, 19, 11, 12],
       [17, 18, 18, 18],
       [16, 13, 13, 13]])

In [26]:
b[:]

array([[15, 14, 17, 19],
       [19, 13, 13, 16],
       [17, 19, 11, 12],
       [17, 18, 18, 18],
       [16, 13, 13, 13]])

In [27]:
b[1:4]

array([[19, 13, 13, 16],
       [17, 19, 11, 12],
       [17, 18, 18, 18]])

In [28]:
b[-1:]

array([[16, 13, 13, 13]])

In [29]:
b[:-1]

array([[15, 14, 17, 19],
       [19, 13, 13, 16],
       [17, 19, 11, 12],
       [17, 18, 18, 18]])

In [30]:
b

array([[15, 14, 17, 19],
       [19, 13, 13, 16],
       [17, 19, 11, 12],
       [17, 18, 18, 18],
       [16, 13, 13, 13]])

In [31]:
b[:-1]

array([[15, 14, 17, 19],
       [19, 13, 13, 16],
       [17, 19, 11, 12],
       [17, 18, 18, 18]])

In [32]:
b[1:3]

array([[19, 13, 13, 16],
       [17, 19, 11, 12]])

In [33]:
b[1,2]

13

In [34]:
b[2,3]

12

In [35]:
b

array([[15, 14, 17, 19],
       [19, 13, 13, 16],
       [17, 19, 11, 12],
       [17, 18, 18, 18],
       [16, 13, 13, 13]])

In [36]:
b[1,-1]

16

**numpy operations**

In [37]:
arr

array([0, 1, 2, 3, 4, 5])

In [38]:
arr.max()

5

In [39]:
arr.min()

0

In [40]:
from numpy import*
a = array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

**Indexing**

In [42]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [50]:
row = 4
col = 6

In [51]:
col

6

In [47]:
mat[row,col]

45

In [52]:
mat[row,col]

46

In [53]:
mat[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [55]:
mat[:,col]#print column

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [56]:
mat[:,3]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [57]:
mat[3]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [58]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [59]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [60]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [61]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [62]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [63]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [65]:
mat[1:2,2:4] #submatrix

array([[12, 13]])

In [66]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

**Masking**

In [67]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [69]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [70]:
mat[mat==50]

array([50])