**Numpy**

In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
import sys
sys.version

'3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]'

In [5]:
# Numpy Array can only store homogeneous types(same data type)

**Creating List**

In [7]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [8]:
type(my_list)

list

**Below code we are converting List into an Array**

In [9]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [12]:
print(type(arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [13]:
np.arange()

TypeError: arange() requires stop to be specified.

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [18]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [19]:
np.arange(10,30,3,3)

TypeError: Cannot interpret '3' as a data type

In [20]:
np.arange(20,10)

array([], dtype=int32)

In [21]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
np.arange(-20,8) #1st arg < 2nd org

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [24]:
n = np.arange(-20,8)
n

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [26]:
np.zeros(3)

array([0., 0., 0.])

In [27]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [29]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((5,3)) #2d array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
nd = np.zeros((5,9),dtype=int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
len(nd)

5

In [36]:
np.ones(3)

array([1., 1., 1.])

In [37]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [41]:
nd1 = np.ones((10,10),dtype=int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [40]:
np.three(3)

AttributeError: module 'numpy' has no attribute 'three'